# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows
init:
  - git config --global core.autocrlf input

# If we are running on Node <6, we must install npm v3 otherwise
# there will be intermitent errors when running `npm install`
environment:
  matrix:
    - nodejs_version: 4.7
      npm_version: ^3.0.0
    - nodejs_version: 4.8
      npm_version: ^3.0.0
    - nodejs_version: 5.6
      npm_version: ^3.0.0
    - nodejs_version: 5.7
      npm_version: ^3.0.0
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 9

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: |
      if ($env:npm_version)
      {
        npm install -g npm@$env:npm_version
      }
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color

after_test:
  - "npm i codecov"
  - "node_modules/.bin/codecov"
